/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubsidiesRouteImport } from './routes/subsidies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubsidiesIndexRouteImport } from './routes/subsidies.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SubsidiesSlugRouteImport } from './routes/subsidies.$slug'
import { Route as AdminSitemapRouteImport } from './routes/admin.sitemap'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRobotsRouteImport } from './routes/admin.robots'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as ServicesSlugIndexRouteImport } from './routes/services.$slug.index'
import { Route as ServicesSlugProductSlugRouteImport } from './routes/services.$slug.$productSlug'

const SubsidiesRoute = SubsidiesRouteImport.update({
  id: '/subsidies',
  path: '/subsidies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsidiesIndexRoute = SubsidiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubsidiesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SubsidiesSlugRoute = SubsidiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubsidiesRoute,
} as any)
const AdminSitemapRoute = AdminSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRobotsRoute = AdminRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugIndexRoute = ServicesSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugProductSlugRoute = ServicesSlugProductSlugRouteImport.update({
  id: '/$slug/$productSlug',
  path: '/$slug/$productSlug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subsidies': typeof SubsidiesRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/sitemap': typeof AdminSitemapRoute
  '/subsidies/$slug': typeof SubsidiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/subsidies/': typeof SubsidiesIndexRoute
  '/services/$slug/$productSlug': typeof ServicesSlugProductSlugRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/sitemap': typeof AdminSitemapRoute
  '/subsidies/$slug': typeof SubsidiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/subsidies': typeof SubsidiesIndexRoute
  '/services/$slug/$productSlug': typeof ServicesSlugProductSlugRoute
  '/services/$slug': typeof ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subsidies': typeof SubsidiesRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/sitemap': typeof AdminSitemapRoute
  '/subsidies/$slug': typeof SubsidiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/subsidies/': typeof SubsidiesIndexRoute
  '/services/$slug/$productSlug': typeof ServicesSlugProductSlugRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/calculator'
    | '/contact'
    | '/partners'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/subsidies'
    | '/admin/about'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/faq'
    | '/admin/home'
    | '/admin/robots'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/site'
    | '/admin/sitemap'
    | '/subsidies/$slug'
    | '/admin/'
    | '/services/'
    | '/subsidies/'
    | '/services/$slug/$productSlug'
    | '/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/contact'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/about'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/faq'
    | '/admin/home'
    | '/admin/robots'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/site'
    | '/admin/sitemap'
    | '/subsidies/$slug'
    | '/admin'
    | '/services'
    | '/subsidies'
    | '/services/$slug/$productSlug'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/calculator'
    | '/contact'
    | '/partners'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/subsidies'
    | '/admin/about'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/contact'
    | '/admin/content'
    | '/admin/faq'
    | '/admin/home'
    | '/admin/robots'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/site'
    | '/admin/sitemap'
    | '/subsidies/$slug'
    | '/admin/'
    | '/services/'
    | '/subsidies/'
    | '/services/$slug/$productSlug'
    | '/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubsidiesRoute: typeof SubsidiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subsidies': {
      id: '/subsidies'
      path: '/subsidies'
      fullPath: '/subsidies'
      preLoaderRoute: typeof SubsidiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subsidies/': {
      id: '/subsidies/'
      path: '/'
      fullPath: '/subsidies/'
      preLoaderRoute: typeof SubsidiesIndexRouteImport
      parentRoute: typeof SubsidiesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/subsidies/$slug': {
      id: '/subsidies/$slug'
      path: '/$slug'
      fullPath: '/subsidies/$slug'
      preLoaderRoute: typeof SubsidiesSlugRouteImport
      parentRoute: typeof SubsidiesRoute
    }
    '/admin/sitemap': {
      id: '/admin/sitemap'
      path: '/sitemap'
      fullPath: '/admin/sitemap'
      preLoaderRoute: typeof AdminSitemapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/robots': {
      id: '/admin/robots'
      path: '/robots'
      fullPath: '/admin/robots'
      preLoaderRoute: typeof AdminRobotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug/': {
      id: '/services/$slug/'
      path: '/$slug'
      fullPath: '/services/$slug/'
      preLoaderRoute: typeof ServicesSlugIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug/$productSlug': {
      id: '/services/$slug/$productSlug'
      path: '/$slug/$productSlug'
      fullPath: '/services/$slug/$productSlug'
      preLoaderRoute: typeof ServicesSlugProductSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminRobotsRoute: typeof AdminRobotsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSitemapRoute: typeof AdminSitemapRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminContentRoute: AdminContentRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminRobotsRoute: AdminRobotsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminSitemapRoute: AdminSitemapRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesSlugProductSlugRoute: typeof ServicesSlugProductSlugRoute
  ServicesSlugIndexRoute: typeof ServicesSlugIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesSlugProductSlugRoute: ServicesSlugProductSlugRoute,
  ServicesSlugIndexRoute: ServicesSlugIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SubsidiesRouteChildren {
  SubsidiesSlugRoute: typeof SubsidiesSlugRoute
  SubsidiesIndexRoute: typeof SubsidiesIndexRoute
}

const SubsidiesRouteChildren: SubsidiesRouteChildren = {
  SubsidiesSlugRoute: SubsidiesSlugRoute,
  SubsidiesIndexRoute: SubsidiesIndexRoute,
}

const SubsidiesRouteWithChildren = SubsidiesRoute._addFileChildren(
  SubsidiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubsidiesRoute: SubsidiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
